import sys
from enigma import *

text = "MILFIRQKFRLQINVOOXQKNWRSQJOOLKEQDPIUYGUMLQPUAXEZIQAVHIFYLGQVGOTMLHBKZZELWELNRBACSWPRSXXBOVRGQZAKNZCMPGYGWBYBWKZBUTBQTXXBUCUCMRVIHQUJFYOQIMWJGKNMVLZPIDTBKXFRKFNVVRVFGGMVIWBXOGAXKEGQUDFUHVADFHYTQKWBMWQOLWAYWBLBPUYCIEGBESAFRXYSXXJRXSRUKMMUSLLPVLACHAXQPVNIQZFSLTYAKVHOTJLYKJMHNGVCTLLVISIUHEMXLNSKDUXPIJIBHFZYXBPANIBUEUAYEBXKHHAFYAVLZVEJQUCXNHVXVNKZATDLHQRBYXYKZXFLTGDBPHLADWRAMCFKVZHRTJBGDDSUILLVGQTYLOHPGQSMQXOHYIJGNPLJJZOLQODFRKAEXTKKJRZUTAKKQGJILTODZHVDEGLWYXEBVAMKCECWYPMWQWZZMKCKRVBDLUOMNWJUDTJXGMCKNUBQCQDRNMGMKXAHOUKNLYWMJPBMDWFDHAFAQZHBTGDKFCGNYOJAONXXMKXOASKCXCOWIZKHWCICWMASAPIQLLJMXWNWJIAZAVNUGDSKPTZJPAWEWWUQEDCJSEXXOJDUWWUBSNWWOIVSFNKFSVPEZHJAIDQGMATMSNDUGUCTDEAHKLELNQBCYHYZAXLNWYDTOUYQCOQHVGRXWXFBJZLORZJZLBTYSFXGYVYKFYDCTVIBOUKDTQBJPTIPYGJGINJVCAXOEQYFDJCPDTESZHWTKJYBOGBHIPDNQVLHWJQERQGLHIPKRYAZJMQHZSEZHJNKEMPEZSXGJJLFXCHXIRGIBSOOCMDONRWSBGZWYCTFBEZYGIFKHFKUKQPGRXDLYHKGENIBATOKHKQDOFJKZFLIYCMJSE"

def brute_ring_settings(ciphertext):
    for a in range(1, 26):
        for b in range(1, 26):
            for c in range(1, 26):
                machine = EnigmaMachine.from_key_sheet(
                   rotors='I II III',
                   reflector='B',
                   ring_settings=[a, b, c],
                   plugboard_settings='AQ BJ')
                plaintext = machine.process_text(ciphertext)
                if "ICECTF" in plaintext:
                    print('[+] Ring settings: {}, {}, {}'.format(a, b, c))
                    return a, b, c
    return -1, -1, -1

a, b, c = brute_ring_settings(text)